apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: prometheus-hello-world
  name: hello-world-prometheus
spec:
  replicas: 2
  ruleSelector:
    matchLabels:
      prometheus-name: hello-world-prometheus
  serviceAccountName: prometheus-k8s
  securityContext: {}
  serviceMonitorSelector:
    matchLabels:
      k8s-app: hello-world
  version: v2.3.2 